#include <stdbool.h>
#include <crankshaft/server.h>
#include <crankshaft/string.h>
#include <crankshaft/util.h>
#include "freezer.h"
//Autogenerated touch at your peril
const struct CS_String googlelogin_uri = CS_STRING("/freezer/googlelogin");
const struct CS_String cookiefilter_uri = CS_STRING("/freezer/cookiefilter");
const struct CS_String api_logbody_uri = CS_STRING("/freezer/api/logbody");
const struct CS_String api_product_putimage_uri = CS_STRING("/freezer/api/product/putimage");
const struct CS_String api_product_putinfo_uri = CS_STRING("/freezer/api/product/putinfo");
const struct CS_String api_product_putnutrition_uri = CS_STRING("/freezer/api/product/putnutrition");
const struct CS_String api_product_deleteimage_uri = CS_STRING("/freezer/api/product/deleteimage");
const struct CS_String api_product_deleteinfo_uri = CS_STRING("/freezer/api/product/deleteinfo");
const struct CS_String api_product_deletenutrition_uri = CS_STRING("/freezer/api/product/deletenutrition");
const struct CS_String api_product_get_uri = CS_STRING("/freezer/api/product/get");
const struct CS_String api_product_delete_uri = CS_STRING("/freezer/api/product/delete");
const struct CS_String api_message_get_uri = CS_STRING("/freezer/api/message/get");
const struct CS_String api_message_delete_uri = CS_STRING("/freezer/api/message/delete");
const struct CS_String api_message_accept_uri = CS_STRING("/freezer/api/message/accept");
const struct CS_String api_message_send_uri = CS_STRING("/freezer/api/message/send");
const struct CS_String api_family_get_uri = CS_STRING("/freezer/api/family/get");
const struct CS_String api_family_invite_uri = CS_STRING("/freezer/api/family/invite");
const struct CS_String api_family_remove_uri = CS_STRING("/freezer/api/family/remove");
const struct CS_String api_item_add_uri = CS_STRING("/freezer/api/item/add");
const struct CS_String api_item_remove_uri = CS_STRING("/freezer/api/item/remove");
const struct CS_String api_section_add_uri = CS_STRING("/freezer/api/section/add");
const struct CS_String api_section_remove_uri = CS_STRING("/freezer/api/section/remove");
const struct CS_String api_section_switch_uri = CS_STRING("/freezer/api/section/switch");
const struct CS_String api_freezer_switch_uri = CS_STRING("/freezer/api/freezer/switch");
const struct CS_String api_freezer_remove_uri = CS_STRING("/freezer/api/freezer/remove");
const struct CS_String api_freezer_add_uri = CS_STRING("/freezer/api/freezer/add");
const struct CS_String api_allow_add_uri = CS_STRING("/freezer/api/allow/add");
const struct CS_String api_allow_remove_uri = CS_STRING("/freezer/api/allow/remove");
const struct CS_String api_allow_ban_uri = CS_STRING("/freezer/api/allow/ban");
const struct CS_String api_wildcard_get_uri = CS_STRING("/freezer/api/wildcard/get");
const struct CS_String api_wildcard_head_uri = CS_STRING("/freezer/api/wildcard/head");
struct CS_Route freezerRoutes[] = {
