#include <stdbool.h>
#include <crankshaft/server.h>
#include <crankshaft/string.h>
//Autogenerated touch at your peril
#ifdef __cplusplus
extern "C" {
#endif
extern struct CS_Route freezerRoutes[];
int32_t numFreezerRoutes(void);
extern const struct CS_String googlelogin_uri; 
extern const struct CS_String cookiefilter_uri; 
extern const struct CS_String logfilter_uri; 
extern const struct CS_String api_logbody_uri; 
extern const struct CS_String api_product_putimage_uri; 
extern const struct CS_String api_product_putinfo_uri; 
extern const struct CS_String api_product_putnutrition_uri; 
extern const struct CS_String api_product_deleteimage_uri; 
extern const struct CS_String api_product_deleteinfo_uri; 
extern const struct CS_String api_product_deletenutrition_uri; 
extern const struct CS_String api_product_get_uri; 
extern const struct CS_String api_product_delete_uri; 
extern const struct CS_String api_message_get_uri; 
extern const struct CS_String api_message_delete_uri; 
extern const struct CS_String api_message_accept_uri; 
extern const struct CS_String api_message_send_uri; 
extern const struct CS_String api_family_get_uri; 
extern const struct CS_String api_family_invite_uri; 
extern const struct CS_String api_family_remove_uri; 
extern const struct CS_String api_item_add_uri; 
extern const struct CS_String api_item_remove_uri; 
extern const struct CS_String api_section_add_uri; 
extern const struct CS_String api_section_list_uri; 
extern const struct CS_String api_section_remove_uri; 
extern const struct CS_String api_section_switch_uri; 
extern const struct CS_String api_section_rename_uri; 
extern const struct CS_String api_freezer_list_uri; 
extern const struct CS_String api_freezer_switch_uri; 
extern const struct CS_String api_freezer_remove_uri; 
extern const struct CS_String api_freezer_add_uri; 
extern const struct CS_String api_freezer_rename_uri; 
extern const struct CS_String api_allow_add_uri; 
extern const struct CS_String api_allow_remove_uri; 
extern const struct CS_String api_allow_ban_uri; 
extern const struct CS_String api_state_uri; 
extern const struct CS_String api_wildcard_get_uri; 
extern const struct CS_String api_wildcard_head_uri; 
#ifdef __cplusplus
}
#endif
